services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: CakePHPApp
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - PHP_INI_DATE_TIMEZONE=America/Recife
      - DATABASE_HOST=db
    restart: always
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    container_name: BancoBlog
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=cakeBlog
      - POSTGRES_PASSWORD=c4k3-rUl3Z
      - POSTGRES_DB=blogdb
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
volumes:
  pgdata: